version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      # Install PHPUnit manually
      - wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
      - chmod +x phpunit
      # Optionally, you can move phpunit to a directory in your $PATH
      - mv phpunit /usr/local/bin/phpunit

  pre_build:
    commands:
      # Optionally, you can run any pre-build tasks here
      # For example, clearing caches, setting up configurations, etc.

  build:
    commands:
      # Run PHPUnit tests
      - phpunit --configuration phpunit.xml

  post_build:
    commands:
      # Optionally, you can perform post-build tasks here
      # For example, deploying your application to AWS Elastic Beanstalk or S3
