version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  pre_build:
    commands:
      - echo "Setting up dependencies..."
      # You can add any pre-build commands here, such as installing Composer dependencies.
      # Example:
      # - composer install
  build:
    commands:
      - echo "Building your PHP application..."
      # Add your build commands here.
      - phpunit
  post_build:
    commands:
      - echo "Build completed successfully!"
      # Add any post-build commands here, such as running tests or deploying.
      # Example:
      # - phpunit
      # - aws deploy command or any other deployment steps
