version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "PHP Version ⬇"
      - php -v
      - echo "Initiation of build 🏠"
      - echo "Installing Composer 🎺"
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Installing dependencies 📦"
      - composer install
      # Add any other necessary installation steps here

  build:
    commands:
      # Run your tests, linters, and other code quality checks
      # Example:
      - echo "Running PHPUnit tests 🧪"
      - phpunit
      # Add more commands as needed

artifacts:
  files:
    - '**/*'  # Include all files in the build artifact